### ISSUE TITLE
SyntaxError in grader.py, question 14

### ISSUE THREAD

**Issue by connortann** [thedataincubator/expo-demo#8]
I had a go answering the questions this morning, encountered a suspected bug:

https://github.com/thedataincubator/expo-demo/blob/310b912421c6b3e2063873288e1629441081fab0/grade.py#L228

This line causes a SyntaxError when the correct answer is submitted. I believe there is an issue with IPython in which decorated multi-line strings are not parsed correctly.

In my VM I made this replacement, which seemed to work at a pinch. It's not an ideal fix as it does require `some_formula` to have already been defined and decorated in the user's namespace.

```python
# grader.py, line 229
'decorator': {
        'initialize': '',
#         'eval_func': check_function('''@ensure_nonneg \ndef some_formula(a, b, c):\n\tresult = 3*a + b - 8*c\n\treturn result \nval=some_formula(2, 3, 5), some_formula(5, 3, 2)''', 'val', (0, 2))
        'eval_func': check_function('some_formula',
                                    ((2, 3, 5), 0),
                                    ((5, 3, 2), 2))
    },
```
FYI @rschroll

**Comment by connortann** [comment]
Some further information, here's the error traceback.

Input:
```python
%%grade decorator

def ensure_nonneg(func):
    # Puzzle solution would go here
    return func

print(42)
```

Output:
```
Traceback (most recent call last):

  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "/tmp/ipykernel_256/709806319.py", line 1, in <module>
    get_ipython().run_cell_magic('grade', 'decorator', '\n1+1\n')

  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2403, in run_cell_magic
    result = fn(*args, **kwargs)

  File "/home/jovyan/grade.py", line 289, in grade
    if result.success and question['eval_func'](ipy):

  File "/home/jovyan/grade.py", line 48, in func
    f = ipy.ev(name)

  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2715, in ev
    return eval(expr, self.user_global_ns, self.user_ns)

  File "<string>", line 1
    @ensure_nonneg
    ^
SyntaxError: invalid syntax
```

**Comment by rschroll** [comment]
Thank for noticing that.  It looks like a bad merge didn't get the new code in correctly.  The updated version should work whether or not the user has decorated `some_function` or not.

@anahocevar You might want to double check me on this.

**Comment by anahocevar** [comment]
Yup, looks good. Thanks for noticing @connortann!
